### PR TITLE
Filesystem Total MNRVA 78

### PR DESCRIPTION
**Pull request by FarajiA**
## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-78

## Description:
Adds filesystem total graph component

## Testing:
`bundle exec jekyll serve`

## Screenshots:
filesystotal

### CODE REVIEW

**Comment by kyleondata** [comment]
the code looks fine, but looking at the screen shot here, do we have a bug in where higher number Y coordinate values fail to show the labels correctly?  Thoughts?

**Comment by FarajiA** [comment]
Right... as the Y axis works now its doing this kinda max calculation. I think we'd have to add some kind of ticker functionality to add a buffer area above the max data point.

**Comment by kyleondata** [comment]
I wonder if it is a margins issue?

**Comment by kyleondata** [comment]
merge conflicts

**Comment by FarajiA** [comment]
Doesn't seem to be the margin from my investigating. I think we'd have to supply some kind of buffer for the max. I can dig into maybe how its being done in Sage currently.

The problem seems reoccurring.

**Comment by terryllowery** [comment]
Cannot run locally because of the package.json file has preinstall: "npm run build" therefore the node_modules are missing.

**Pull request merged**
