### PR TITLE
Vunerabilities fix packagejson

### PR DESCRIPTION
**Pull request by FarajiA**
## JIRA:
N/A: See ticket here - https://jira.rax.io/browse/MNRVA-XXXX

## Description:
Fixes the outdated package dependencies, as it turns out PhantomJS dependencies were still hanging around in the package.json

## Screenshots:
(if applicable)

### CODE REVIEW

**Comment by kyleondata** [comment]
can we go ahead and start pinning deps listed in our package.json?

**Comment by FarajiA** [comment]
Sure, you mean not using `^`? I will update

**Comment by kyleondata** [comment]
right no symbols

**Comment by FarajiA** [comment]
This was merged

**Pull request closed without merging**
